# Generated by Django 6.0.5 on 2026-05-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='Название')),
                ('anons', models.CharField(default='', max_length=250, verbose_name='Анонс')),
                ('full_text', models.TextField(default='', max_length=50, verbose_name='Текст новости')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
    ]
