# Generated by Django 6.0.5 on 2026-05-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_artiles_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiles',
            name='full_text',
            field=models.TextField(default='', max_length=500, verbose_name='Текст новости'),
        ),
    ]
