# Generated by Django 6.0.5 on 2026-05-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_artiles_dislikes_artiles_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='artiles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Изображение'),
        ),
    ]
