# Generated by Django 6.0.5 on 2026-05-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_artiles_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='main/image/', verbose_name='Изображение'),
        ),
    ]
